<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Detection\\' => array($vendorDir . '/mobiledetect/mobiledetectlib/src'),
);
