{**
* 2010-2021 Webkul.
*
* NOTICE OF LICENSE
*
* All right is reserved,
* Please go through LICENSE.txt file inside our module
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade this module to newer
* versions in the future. If you wish to customize this module for your
* needs please refer to CustomizationPolicy.txt file inside our module for more information.
*
* @author Webkul IN
* @copyright 2010-2021 Webkul IN
* @license LICENSE.txt
*}

<div class="col-sm-12">
	<section id="dashperformance" class="panel widget {if $allow_push} allow_push{/if}">
		<header class="panel-heading">
			<i class="icon-bar-chart"></i> {l s="Performance" mod="dashperformance"}
			<span class="panel-heading-action">
				<a class="list-toolbar-btn" href="#" onclick="refreshDashboard('dashperformance'); return false;" title="{l s="Refresh" mod="dashperformance"}">
					<i class="process-icon-refresh"></i>
				</a>
			</span>
		</header>
		<section>
			<div class="row">
				<div class="col-xs-6 col-lg-3">
					<div class="avg-daily-rate preformance-index-wrapper label-tooltip" data-toggle="tooltip" data-original-title="{l s="The Average Daily Rate represents the average rental income per paid occupied room over a given time period." mod="dashperformance"}" data-placement="top">
						<div class="title-wrapper">
							<p>{l s="Avg. Daily Rate" mod="dashperformance"}</p>
						</div>
						<div class="value-wrapper" id="dp_average_daily_rate" style="color: #0093BA">
							{if isset($average_daily_rate)}{$average_daily_rate|escape:"html":"UTF-8"}{/if}
						</div>
					</div>
				</div>
				<div class="col-xs-6 col-lg-3">
					<div class="circle cancellation-rate preformance-index-wrapper label-tooltip" data-toggle="tooltip" data-original-title="{l s="The Cancellation Rate is a percentage of all cancelled orders out of all orders over a given time period." mod="dashperformance"}" data-placement="top">
						<div class="title-wrapper">
							<p>{l s="Cancellation Rate" mod="dashperformance"}</p>
						</div>
						<div class="value-wrapper" id="dp_cancellation_rate" style="color: #FF4036">
							{if isset($cancellation_rate)}{$cancellation_rate|escape:"html":"UTF-8"}{/if}
						</div>
					</div>
				</div>
				<div class="col-xs-6 col-lg-3">
					<div class="circle revenue preformance-index-wrapper label-tooltip" data-toggle="tooltip" data-original-title="{l s="The Revenue is the total amount of income generated by the sale of rooms." mod="dashperformance"}" data-placement="top">
						<div class="title-wrapper">
							<p>{l s="Revenue" mod="dashperformance"}</p>
						</div>
						<div class="value-wrapper" id="dp_revenue" style="color: #00B200">
							{if isset($revenue)}{$revenue|escape:"html":"UTF-8"}{/if}
						</div>
					</div>
				</div>
				<div class="col-xs-6 col-lg-3">
					<div class="circle nights-stayed preformance-index-wrapper label-tooltip" data-toggle="tooltip" data-original-title="{l s="The Nights Stayed is the total number of nights guests occupied over a given time period." mod="dashperformance"}" data-placement="top">
						<div class="title-wrapper">
							<p>{l s="Nights Stayed" mod="dashperformance"}</p>
						</div>
						<div class="value-wrapper" id="dp_nights_stayed" style="color: #E09400">
							{if isset($nights_stayed)}{$nights_stayed|escape:"html":"UTF-8"}{/if}
						</div>
					</div>
				</div>
			</div>
		</section>
	</section>
</div>
<div class="clearfix"></div>
